name: "Podman Setup"
description: "Sets up Podman"
runs:
  using: "composite"
  steps:
    - name: Install Podman
      uses: redhat-actions/podman-install@5bc2ecc87c737059124c295845be51ee7297fb89
      with:
        ubuntu-repository: kubic
        ubuntu-version: "24.04"

    - name: Configure Podman
      shell: bash
      run: |
        sudo systemctl enable --now podman.socket
        podman --url=unix:///run/podman/podman.sock info
        echo "DOCKER_HOST=unix:///run/podman/podman.sock" >> $GITHUB_ENV
        echo "CI_PODMAN=true" >> $GITHUB_ENV
