name: "Podman Setup"
description: "Sets up Podman"
runs:
  using: "composite"
  steps:
    - name: Install Podman
      uses: redhat-actions/podman-install@main
      with:
        podman-version-input: 5.4.2

    - name: Configure Podman
      shell: bash
      run: |
        systemctl enable --now --user podman podman.socket
        podman info
        echo "DOCKER_HOST=unix://${XDG_RUNTIME_DIR}/podman/podman.sock" >> $GITHUB_ENV
        echo "CI_ROOTLESS=true" >> $GITHUB_ENV
        echo "CI_PODMAN=true" >> $GITHUB_ENV
