name: "Podman Setup"
description: "Sets up Podman"
runs:
  using: "composite"
  steps:
    - name: Verify Podman
      shell: bash
      run: podman --version

    - name: Configure Podman
      shell: bash
      run: |
        sudo systemctl start podman.socket
        PODMAN_SOCKET="$(sudo podman info --format '{{ .Host.RemoteSocket.Path }}')"
        podman --url="unix://${PODMAN_SOCKET}" info
        echo "DOCKER_HOST=unix://${PODMAN_SOCKET}" >> $GITHUB_ENV
        echo "CI_PODMAN=true" >> $GITHUB_ENV
