const MGMT_PORT = 8091;
const MGMT_SSL_PORT = 18091;
const VIEW_PORT = 8092;
const VIEW_SSL_PORT = 18092;
const QUERY_PORT = 8093;
const QUERY_SSL_PORT = 18093;
const SEARCH_PORT = 8094;
const SEARCH_SSL_PORT = 18094;
const ANALYTICS_PORT = 8095;
const ANALYTICS_SSL_PORT = 18095;
const EVENTING_PORT = 8096;
const EVENTING_SSL_PORT = 18096;
const KV_PORT = 11210;
const KV_SSL_PORT = 11207;

export default {
  MGMT_PORT,
  MGMT_SSL_PORT,
  VIEW_PORT,
  VIEW_SSL_PORT,
  QUERY_PORT,
  QUERY_SSL_PORT,
  SEARCH_PORT,
  SEARCH_SSL_PORT,
  ANALYTICS_PORT,
  ANALYTICS_SSL_PORT,
  EVENTING_PORT,
  EVENTING_SSL_PORT,
  KV_PORT,
  KV_SSL_PORT,
};
