name: 'NPM Setup'
description: 'Sets up Node.js and installs NPM dependencies with caching'

inputs:
  runner:
    description: 'Runner to use'
    required: true
  node-version:
    description: 'Node.js version to use'
    required: true
  workspace:
    description: 'Key for the cache'
    required: true

runs:
  using: "composite"
  steps:
      - name: Install NodeJS ${{ inputs.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
      - uses: actions/cache/restore@v4
        id: npm-cache
        with:
          path: node_modules
          # the key is built using both package-lock.json files: the one in the root dir and the one for the module to be built
          key: ${{ inputs.runner }}-node-${{ inputs.node-version }}-${{ inputs.workspace }}-${{ hashFiles(format('{0}-{1}/{2}', 'package-lock.json', inputs.workspace, 'package-lock.json')) }}
          restore-keys: |
            ${{ inputs.runner }}-node-${{ inputs.node-version }}-${{ inputs.workspace }}-
      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        shell: bash
        run: npm ci --omit=optional -- ${{ inputs.workspace }}
      - name: Cache npm
        id: cache-npm-save
        if: steps.npm-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: |
            node_modules
            ${{ inputs.workspace }}/node_modules
          key: ${{ steps.npm-cache.outputs.cache-primary-key }}
