name: 'NPM Setup'
description: 'Sets up Node.js and installs NPM dependencies with caching'

inputs:
  runner:
    description: 'Runner to use'
    required: true
  node-version:
    description: 'Node.js version to use'
    required: true

runs:
  using: "composite"
  steps:
      - name: Install NodeJS ${{ inputs.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
      - uses: actions/cache/restore@v4
        id: npm-cache
        with:
          path: node_modules
          key: ${{ github.head_ref || 'main' }}-${{ inputs.runner }}-node-${{ inputs.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ github.head_ref || 'main' }}-${{ inputs.runner }}-node-${{ inputs.node-version }}-
      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        shell: bash
        run: npm ci --omit=optional
      - name: Cache npm
        id: cache-npm-save
        if: steps.npm-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: node_modules
          key: ${{ steps.npm-cache.outputs.cache-primary-key }}
