name: 'NPM Setup'
description: 'Sets up Node.js and installs NPM dependencies with caching'

inputs:
  runner:
    description: 'Runner to use'
    required: true
  node-version:
    description: 'Node.js version to use'
    required: true

runs:
  using: "composite"
  steps:
      - name: Install NodeJS ${{ inputs.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
      - uses: actions/cache@v4
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ inputs.runner }}-node-${{ inputs.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ inputs.runner }}-node-${{ inputs.node-version }}-
      - name: Install dependencies
        shell: bash
        run: npm ci --omit=optional
      - name: Cache npm
        id: cache-npm-save
        uses: actions/cache/save@v4
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ steps.npm-cache.outputs.cache-primary-key }}
