name: Coverage

on:
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Code checkout
      uses: actions/checkout@v3
    - name: Coverage
      uses: ArtiomTr/jest-coverage-report-action@v2
