name: Node.js Package

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          ref: main

      - uses: actions/setup-node@v6
        with:
          node-version: 24.x
          registry-url: "https://registry.npmjs.org"
          package-manager-cache: false

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Update versions
        run: |
          TAG="${{ github.event.release.tag_name }}"
          VERSION="${TAG#v}"

          npm version "$VERSION" --ws --allow-same-version --no-git-tag-version

          for module in packages/modules/*; do
            npm pkg set "dependencies.testcontainers=^$VERSION" -w "$module"
          done

          npm install --package-lock-only --ignore-scripts

          sed -i -E "s/(sonar.projectVersion)=.+/\1=$TAG/" sonar-project.properties

      - name: Build packages
        run: |
          npm ci
          npm run build --ws

      - name: Git commit and push
        run: |
          git commit -am "${{ github.event.release.tag_name }}"
          git push

      - name: Publish packages to NPM
        run: npm publish --ws
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
