name: NPM Install
run-name: "Runner (${{ inputs.runner }}) / Node (${{ inputs.node-version }})"

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
      node-version:
        required: true
        type: string

jobs:
  npm-install:
    name: "NPM Install (${{ inputs.runner }}) / Node (${{ inputs.node-version }})"
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Install NodeJS ${{ inputs.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
      - uses: actions/cache@v4
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ inputs.runner }}-node-{{ inputs.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ inputs.runner }}-node-{{ inputs.node-version }}-
      - name: Install dependencies
        run: npm ci --omit=optional
