# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os-version }}
    strategy:
      matrix:
        os-version: [ubuntu-latest]
        node-version: [14.x, 16.x, 18.x]
    steps:
    - name: Code checkout
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: cristianrgreco
        password: b62e3c19-4990-46f6-b221-55cf0bfb6513 # read-only
    - name: Install NodeJS ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci --omit=optional
    - name: Run tests
      run: npm run test:ci
    - name: Upload coverage report
      if: ${{ matrix.node-version == '18.x' }}
      uses: actions/upload-artifact@v3
      with:
        name: master-test-coverage
        path: coverage-report.json
#    - name: Create coverage badge
#      if: ${{ matrix.node-version == '18.x' }}
#      uses: schneegans/dynamic-badges-action@v1.6.0
#      with:
#        auth: ${{ secrets.GIST_SECRET }}
#        gistID: 40650417da253155c3a1b61da381da37
#        filename: coverage-badge.json
#        label: coverage
#        color: green
#        message: 90%

  smoke-test:
    runs-on: ${{ matrix.os-version }}
    strategy:
      matrix:
        os-version: [ubuntu-latest]
        node-version: [14.x, 16.x, 18.x]
    steps:
    - name: Code checkout
      uses: actions/checkout@v3
    - name: Install NodeJS ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci --omit=optional
    - name: Remove dev dependencies
      run: npm prune --omit=dev
    - name: Run tests
      run: node smoke-test.mjs
